name: liedar
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  intl: any
  share_plus: ^7.2.1
  fl_chart: ^0.65.0
  image_picker: ^0.8.5+3

  timeago: ^3.2.2
  video_player: ^2.8.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  audioplayers: ^5.2.1
  badges: ^3.1.2
  path_provider: ^2.1.3
  permission_handler: ^10.4.0
  firebase_core: ^3.1.8
  firebase_messaging: ^15.0.0
  file_picker: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/sounds/notification.mp3